### ISSUE TITLE
probleme de variables

### ISSUE THREAD

**Issue by Loodoor** [Reiex/Endless-caves#1]
hey !
dans ton main.py, a partir de la ligne 161 tu declares une variable map
or, python a une fonction nommée map ! du coup, a un moment donnée, tu voudras utiliser (peut etre) cette fonction, et ca ne marchera pas :P

**Comment by Reiex** [comment]
La fonction map ne me servira a rien et de ce que j'ai compris, on peut toujours faire sans, donc je m'en passerais =)
