### ISSUE TITLE
[enhancement] class Hitbox, classes.py

### ISSUE THREAD

**Issue by SuperFola** [Reiex/Endless-caves#2]
hello :D 

ta class hitbox pourrait etre optmisée pour rendre plus facile la detection des collisions :) apres tu prends ou pas, c'est juste pour te montrer comment je ferais (c'est ce que j'utilisais en C avec la SDL, mais sous une forme un peu différente, ok ^^)

``` python
class Hitbox:
    def __init__(self):
        self.x = 0
        self.y = 0
        self.w = 0
        self.h = 0

    def set_hibox(self, new_x, new_y, new_w, new_h):
        #j'utilise des accesseurs pour modifier mes variables perso :D 
        self.x = new_x
        self.y = new_y
        self.w = new_w
        self.h = new_h

    def move_hitbox(self, new_x, new_y):
        self.x = new_x
        self.y = new_y

    def collide(self, hitbox):
        if self.x <= hitbox.x <= self.x + self.w and self.y <= hitbox.y <= self.y + self.h:
            return True
        if hitbox.x <= self.x <= hitbox.x + hitbox.w and hitbox.y <= self.y <= hitbox.y + hitbox.h:
            return True
        return False
```

dans la fonction collide, ca dois te paraitre bizarre je pense.
en fait je regarde si moi, je collide avec la hitbox passée en paramètre (si elle me rentre dedans). si oui, je return True pour dire : je collide !
puis je regarde si la hotbox passée en paramètre collide avec moi, donc si JE suis dans cette hitbox, je fais l'inverse (sinon tu vas louper quelques collisions :/ ). si oui je return True.
enfin, si aucun des 2 tests n'a renvoyé True, donc terminé la fonction, je return False, tu peux passer, il n'y a pas de collisions :)

**Comment by Reiex** [comment]
Pour l'instant, les méthodes de class sont un peu obscures pour moi, donc je prefere faire ça avec des fonctions, meme si c'est un peu moins lisible et ensuite... le système de hitbox, j'ai du le refaire beaucoup de fois et je suis toujours pas sûre du résultat final, bref c'est le bordel... Mais je garde ton code dans un coin de ma tete si jamais je décide de tout refaire manière POO ^^
